server:
  port: 8081
  servlet:
    context-path: /
  address: 127.0.0.1

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.132.161.177:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: hhs2022
  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  typeAliasesPackage: com.qingspring.demo.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: D:/Tools/Project/Image/

system-params:
  web:
    address: localhost
    port: 8080



#accessFile:
#  resourceHandler: /file/** #匹配需要拦截的URL
#  location: D:/Tools/Project/Image/  #本地文件夹